### ISSUE TITLE
Errors with Installing Packages to Run Stray

### ISSUE THREAD

**Issue by Abigiris** [ISSTA-2022-Submission/ExTyper#1]
Hi! Thank you for providing Stray as I am in need of a Python type recommendation tool. However, I encountered some errors while trying to install Stray.

I created and activated a Python 3.9 environment. But when I ran `pip install -r requirements.txt`, the following error occurred:
<img width="599" alt="image" src="https://github.com/ksun212/Stray/assets/32388079/7cac6587-0b0d-41eb-a24a-3857e0518e7c">

This seems to be related to the package 'checklist'. Even when I tried skipping 'checklist', I encountered other errors related to packages like 'allennlp' and 'torch'.

I'm not sure if I have misconfigured something or if the dependencies for Stray need to be updated. Also, could you provide the list of necessary packages only for running Stray (as I don't intend to reproduce)?

I’m looking forward to your prompt response. 
Thank you!

**Comment by ksun212** [comment]
Hello! Thank you for your attention to this project! There may be something wrong with the dependencies. However, as I haven't been working on this project for a long time, correcting them may take some time. 

I will try to correct the dependencies when I am free. Hopefully, it can be finished in a week, as well as the minimal dependency as you mentioned. However, if you need it rapidly, I recommend you build the yourself. As I mentioned in the readme file, Stray is basically a modified version of mypy, so a possible approach is to first try to install mypy (it shares the same dependencies as Stray), then try to run Stray on your own file, see if there are other packages in need and install them.

**Comment by ksun212** [comment]
Hello, I have provided the minimal requirement and tested it on a new ubuntu 22.04 server. Please try using it to setup stray. 
Thanks for catching the dependency broken, feel free to contact again if you have any further problem.
